### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by MrGreenTea** [landscapeio/pylint-django#107]
Since https://github.com/PyCQA/pylint/commit/2fa1375777a1314051ae5f7945ef4e189f30a5e4#diff-08a33e30cbe1275c00410d2ae41028e1 removed make_tests in pylint.testutils, the tests don't run anymore.

**Comment by vinaypai** [comment]
This is the commit that removed other references to make_tests in pylint https://github.com/PyCQA/pylint/commit/5ff3e04e423036fa7cf65fe3ed38e76f3a1e821d
