### ISSUE TITLE
Repo is dead - I've made a fork

### ISSUE THREAD

**Issue by colinhowe** [landscapeio/pylint-django#112]
Upgrading to pylint 1.8.1 has made this repo no longer work.

Various people have made PRs that fix this repo, however, it appears this repo is inactive.

Therefore, I've made a fork:

https://pypi.python.org/pypi/pylint-django-forked
https://github.com/JuggleJobs/pylint-django-forked/

PRs are welcome. I'm also looking for an additional maintainer to help prevent this useful repo from falling into disrepair should I not be around to maintain it for whatever reason.

**Comment by atodorov** [comment]
@colinhowe I've also made a fork about the same time you did at 
https://github.com/MrSenko/django-pylint and also merged pending pull requests and updated the way tests are executed. 

I see you've also made some changes. Are you interested in merging the two forks? Maybe crate a GitHub organization. Please PM me or find me on #freenode.

**Comment by colinhowe** [comment]
Hah. Amazing :)

I'm happy to kill my fork. I only merged the two bits that I needed to get this working with pylint 1.8 and there's nothing else different (apart from the name).

I'm happy to become a maintainer on your fork if you need some help getting PRs merged and released onto pypi. Feel free to add me.

Alternatively, I can create an organisation so that we can keep it alive if one of us moves on.

**Comment by carlio** [comment]
@colinhowe @atodorov Hey both - I could just give you both access to this repo? I know I've been a bit, erm, bad at keeping it updated so I'm happy to pass on the reigns and help out where I can.

**Comment by colinhowe** [comment]
I'm happy with that. Would need access to upload to pypi too.

Hi btw! :D

**Comment by carlio** [comment]
@colinhowe sure - just figuring out how to do that! What's your PyPI username? 

Also Hi ;)

**Comment by atodorov** [comment]
@carlio  +1 from me as well (give us access to this repo and PyPI) but I've gone ahead and made some changes in my fork that may not be very welcome. In particular I've dropped testing on Python 2 and older Django versions. I'm currently testing with 1.11.x and 2.0+ on Python 3.5 and 3.6.

I can make a PR with all of my changes (including other pending PRs) and after it is merged we can kill the forks? How about that ?

**Comment by colinhowe** [comment]
I'm colinhowe on pypi.

I'm happy to see Python 2 support dropped to be honest.

**Comment by atodorov** [comment]
I am atodorov on PyPI, going to make that huge PR now and remove some of the bits I've customized.

**Comment by carlio** [comment]
I would prefer to keep hold of py2 support for a little while longer but if it's a huge problem I have no particular worry with removing it. That would also mirror pylint's approach (https://github.com/PyCQA/pylint/issues/1763)

Added you both to the repo, will see how to do that in pypi too. (For what it's worth I have no problem with forks existing just figured out that this repo is where links exist on sites so might as well at least redirect to more maintained versions!)

**Comment by carlio** [comment]
Ok done on PyPI too.

**Comment by colinhowe** [comment]
Woo! Thanks Carl :)

Re: Py2. We can tag the current version as the last supporting Python2 so that people can at least find it easily and make PRs against that if they want. I've no objection to Python2 support continuing - I just don't want to spend my time on it

**Comment by atodorov** [comment]
https://github.com/landscapeio/pylint-django/pull/113 is now ready for review. Let's move the conversation there.

**Comment by atodorov** [comment]
@colinhowe I'm closing this issue. Whether or not you remove your fork from pypi is up to you.

I think we are ready to release 0.8.0 as soon as #114 gets merged.

**Comment by colinhowe** [comment]
I'll remove my fork from github and pypi as soon as I update my app to use the new version of this :)

**Comment by colinhowe** [comment]
Just to close the loop: completely removed my fork from github and pypi

**Comment by bittner** [comment]
This repo is now under the PyCQA umbrella. And still needs to improve on maintenance. (Power entails responsibility!)

Re Python 2, if I'm allowed to say my opinion, I'd either tie this decision to PyLint, or have all Python versions supported that are supported by the latest supported versions of Django. After all, this project depends on those two tools/frameworks.
I'm not a big fan of Python 2, don't get me wrong. I prefer sensible decisions over strict personal preference, though.

**Comment by bittner** [comment]
Ouuh, sorry! This thread is only a week old!  :rofl: 

Please, don't be offended!
