### ISSUE TITLE
Custom model managers don't work

### ISSUE THREAD

**Issue by carlio** [landscapeio/pylint-django#31]
Custom model managers have several errors of the form:

```
Instance of 'UserManager' has no 'exclude' member
```

**Comment by smirolo** [comment]
I had the same issue when upgrading from Django 1.6 to Django 1.7. This is related to [Calling custom QuerySet methods from the Manager](https://docs.djangoproject.com/en/1.7/releases/1.7/#calling-custom-queryset-methods-from-the-manager) in the release notes.

I solved it two different ways:

1. Replace custom Managers by custom QuerySets and replace objects = CustomerManager() by objects = CustomQuerySet.as_manager().

2. Put a [workaround in pylint_django/augmentations/__init__.py](https://github.com/smirolo/pylint-django/commit/fa032b6921c6a0036e2ef1e5de0f02be3bcdb228).

**Comment by mitchelljkotler** [comment]
I'm having this issue also, any chance your fixed gets pulled in?

**Comment by carlio** [comment]
Fixed in `0.6.1`. @smirolo I pulled in your change, thanks!

**Comment by mitchelljkotler** [comment]
Thanks!
