### ISSUE TITLE
Infinite loop calculating mro in astroid>=1.3.3

### ISSUE THREAD

**Issue by carlio** [landscapeio/pylint-django#37]
As of astroid 1.3.3, class method resolution order is taken into consideration: https://bitbucket.org/logilab/astroid/commits/b1d8107715a4ceeeeb3f4a9065b67817e8cdc643

This caused an infinite loop when using pylint-django, as the model and form field transforms extended the base Django object then replaced it. This caused the MRO lookup to find a class as its own ancestor.

**Comment by akshayjshah** [comment]
Any chance of cutting a new release with this fix?

**Comment by carlio** [comment]
@akshayjshah I've been working on it but so far all my solutions have had the same problem. Getting closer though!

**Comment by akshayjshah** [comment]
Gotcha - thanks!

**Comment by carlio** [comment]
In the end I submitted a PR to astroid itself too: https://bitbucket.org/logilab/astroid/pull-request/67/mro-lookups-can-get-into-an-infinite-loop

However I don't know when that will be released so I've also patched pylint-django. Once I've verified it builds and the tests pass, and fixed a couple of small remaining bugs, I'll create a new PyPI release.
