### ISSUE TITLE
HttpResponse

### ISSUE THREAD

**Issue by abrahammartin** [landscapeio/pylint-django#42]
Django test suites using self.client.get or self.client.post return HttpResponse, HttpResponseNotFound, HttpResponseServerError, HttpResponseRedirect, or WSGIRequest.

If you want to test the url of a HttpResponseRedirect you can check its url member. 

    response = self.client.get(reverse(views.index))
    self.assertEqual(response.status_code, 302)  # Not logged in, redirected to login
    self.assertEqual(response.url, reverse('login'))

It works fine and the third line is not executed unless response is HttpResponseRedirect. You could also add
    self.assertEqual(response.__class__, HttpResponseRedirect)

but in both cases pylint returns

    p1/tests.py:47: [E1101(no-member), P1Tests.test_index] Instance of 'WSGIRequest' has no 'url' member
    p1/tests.py:47: [E1101(no-member), P1Tests.test_index] Instance of 'HttpResponseServerError' has no 'url' member
    p1/tests.py:47: [E1101(no-member), P1Tests.test_index] Instance of 'HttpResponseNotFound' has no 'url' member
    p1/tests.py:47: [E1101(no-member), P1Tests.test_index] Instance of 'HttpResponse' has no 'url' member

any idea how to get rid of these errors?

I could add 'url' to 'generated-members' and the errors would disappear but it is not a good solution.

**Comment by degustaf** [comment]
Django already solved this issue for you.  [AssertRedirect](https://docs.djangoproject.com/en/1.9/topics/testing/tools/#django.test.SimpleTestCase.assertRedirects) allows you to test all of this in one statement that pylint has no problems with.

```
response = self.client.get(reverse(views.index))  # Not logged in, redirected to login
self.assertRedirect(response.status_code, reverse('login'))
```

**Comment by carlio** [comment]
ok will close this as seems like the solution is a code change rather than a plugin change, let me know if you disagree!
