### ISSUE TITLE
Foreign key related name producing no-member error message when using first() and last()

### ISSUE THREAD

**Issue by abbottc** [landscapeio/pylint-django#49]
Code such as the following isn't currently filtered by pylint-django, and so results in a `no-member` error message in pylint:

    <model>.<related_name>.first()
    <model>.<related_name>.last()

(Django 1.6 was the version where `first()` and `last()` were added to the queryset API)

Fixing this would just seem to require adding the items 'first' and 'last' to the [manager_attrs](https://github.com/landscapeio/pylint-django/blob/b51fc5f3db3c030a48807703edacb601becbbe96/pylint_django/augmentations/__init__.py#L72) list.  Would that be possible, or are the words 'first' and 'last' considered too generic and a risk for false positives?

**Comment by carlio** [comment]
@abbottc I know this is super old, sorry about that! I'm going through cleaning up old issues and can't seem to reproduce using pylint 1.5. If you still have your old venv lying around, could you try upgrading and see if that fixes the issue?

**Comment by abbottc** [comment]
It's no problem that it's an old ticket.  Better late than never, and I realize it's a lot of work maintaining an open source project and sometimes things get behind.  I was able to confirm what you said.  I ran a test using both pylint 1.4.4 and 1.5.5.  The issue showed up with 1.4 and is now fixed in 1.5.  Thanks for following up on it!

**Comment by andrelaszlo** [comment]
This problem seems to be back?

**Comment by gustavoaca1997** [comment]
I am having the same problem

**Comment by pktiuk** [comment]
Me too.
