### ISSUE TITLE
No name 'models' in module 'django.db'

### ISSUE THREAD

**Issue by Ghopper21** [landscapeio/pylint-django#54]
Without the pylint_django plugin, pylint is silent on the line:

```
from django.db.models import Q
```

With it, pylint gives the error:

```
[no-name-in-module] No name 'models' in module 'django.db'
```

**Comment by carlio** [comment]
Can you let me know if that's still an issue and what versions of pylint and django you have? Errors like that are mostly due to pylint detecting locally installed libraries so it may just be a version mismatch.
