### ISSUE TITLE
View.kwargs is an unsubscriptable-object

### ISSUE THREAD

**Issue by danni** [landscapeio/pylint-django#61]
The following code generates an error:

        return super().get_queryset()\
            .filter(capability=self.kwargs['capability'])

views.py [unsubscriptable-object] Value 'self.kwargs' is unsubscriptable [python/pylint]

**Comment by art-solopov** [comment]
+1.

I'm getting pretty much the same error.

**Comment by carlio** [comment]
think @danni fixed this in https://github.com/landscapeio/pylint-django/pull/67 which is now in master, will make new release soon.
