### ISSUE TITLE
_meta is official API

### ISSUE THREAD

**Issue by koterpillar** [landscapeio/pylint-django#66]
With `_meta` being brought into the public API, it makes sense to exclude it from `protected-access`.

**Comment by carlio** [comment]
@koterpillar do you have an example where this is triggered? I just created a test-case for this and it seems like `protected-access` is not raised. I tried with django 1.9 and 1.7 and both seemed ok. What version of pylint are you running?

**Comment by koterpillar** [comment]
Please try `MODEL._meta.get_field('ursuary')` in your example.

**Comment by carlio** [comment]
@koterpillar Ah brilliant thanks, test is now failing, so I'll look into suppressing that warning :+1:

**Comment by carlio** [comment]
Fixed in develop branch with https://github.com/landscapeio/pylint-django/commit/e044f83b5db0148b11bd89abfb5c2bb084de0247 , will add to a release soon
