### ISSUE TITLE
mongoengine.Document.objects is not callable

### ISSUE THREAD

**Issue by Coldwings** [landscapeio/pylint-django#75]
In the fake module mongoengine, the fake Document class is defined as
```python
from mongoengine.errors import DoesNotExist, MultipleObjectsReturned

class Document(object):
    _meta = None
    objects = None

    id = None
    pk = None

    MultipleObjectsReturned = MultipleObjectsReturned
    DoesNotExist = DoesNotExist

    save = lambda: None
```
which member objects gives a None. The fact in mongoengine it should be a mongoengine.QuerySetManager, which is callable, and can be used as query method.

For now, the code
`SomeDocument.objects(query)`
pylint gives out a E1102. That should be fixed.

**Comment by carlio** [comment]
Merged https://github.com/landscapeio/pylint-django/pull/76 so will make a release soon, thanks!
