### ISSUE TITLE
Disabling pylint_django error messages from command line

### ISSUE THREAD

**Issue by aswinm** [landscapeio/pylint-django#86]
When adding messages like model-missing-unicode or model-unicode-not-callable to the disable parameter in the pylint config file does not ignore the errors. The errors get ignored only when they are specified in each file.

**Comment by kiciek** [comment]
Have you tried disabling them in config file for pylint like this?
`cat ~/.pylintrc
[MASTER]

load-plugins=pylint_django
max-line-length=119
disable=C0111
`

**Comment by atodorov** [comment]
No reply from OP for over a year. Closing. Please reopen with proper steps to reproduce if still an issue with the latest available version.
